### ISSUE TITLE
Obtaining the weights of the model

### ISSUE THREAD

**Issue by GlebSBrykin** [tensorlayer/adaptive-style-transfer#3]
Hi! I am engaged in the implementation of various interesting algorithms in C#. I would like to implement this app, however it would require weights of trained models. Could You convert weight in JSON or binary format so I was able to use them? In advance-thank you for the answer.

**Comment by DEKHTIARJonathan** [comment]
Dear friend,

I'm sorry but all of us are really busy. And we prefer spending time on improving the library.

Feel free to install the project and do it yourself...

Jonathan

**Comment by GlebSBrykin** [comment]
Is it possible to install the project in Windows?

**Comment by DEKHTIARJonathan** [comment]
Absolutely, have a look to tensorlayer project.
